services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile.fastapi.dev
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file: .env.fastapi

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]

  nextjs-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev.nextjs
    env_file: ./frontend/.env.local
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    depends_on:
      - fastapi
      - redis
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod.nextjs
    env_file: ./frontend/.env.production
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - fastapi
    profiles:
      - production

volumes:
  redis_data:
